export const AUTH_TYPE = {
    SET_RESULTS_DATA: "SET_RESULTS_DATA",
    SET_VERIFICATION_CODE: "SET_VERIFICATION_CODE",
    SET_USER_DATA: "SET_USER_DATA",
    SET_REFERRAL_CODE: "SET_REFERRAL_CODE",
    // Reset to Initial Auth State
    CLEAR_AUTH_STATE: "CLEAR_AUTH_STATE", 
};